apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apacke
spec:
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: apache:latest
        name: apache
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-load-balancer
  labels:
    app  : apache
spec:
  selector:
    app: apache
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
  type: LoadBalancer
